# Generated by Django 5.1.1 on 2024-10-07 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=400, verbose_name='Kriteriýa aňlatmalary')),
                ('max_value', models.IntegerField(verbose_name='Göterimi')),
            ],
            options={
                'verbose_name': 'kriteriýa',
                'verbose_name_plural': 'kriteriýalar',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ugur')),
            ],
            options={
                'verbose_name': 'ugur',
                'verbose_name_plural': 'ugurlar',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality_type', models.CharField(choices=[('Fiziki', 'Fiziki'), ('Ýuridiki', 'Ýuridiki')], default='Fiziki', max_length=50, verbose_name='Şahs görnüşi')),
                ('agency', models.CharField(max_length=200, verbose_name='Edara')),
                ('place_of_residence', models.CharField(max_length=200, verbose_name='Ýaşaýan ýeri')),
                ('full_name_of_manager', models.CharField(max_length=200, verbose_name='Topar ýolbaşçysynyň F.A.Aa')),
                ('full_name_of_second_participant', models.CharField(blank=True, max_length=200, null=True, verbose_name='Toparyň ikinji agzasyňyň F.A.Aa')),
                ('full_name_of_third_participant', models.CharField(blank=True, max_length=200, null=True, verbose_name='Toparyň üçinji agzasyňyň F.A.Aa')),
                ('phone_number', models.CharField(max_length=8, verbose_name='Telefon belgi')),
                ('additional_phone_number', models.CharField(max_length=8, verbose_name='Telefon belgi')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Taslamanyň beýany')),
                ('rated', models.BooleanField(default=False)),
                ('p_copy_page1', models.ImageField(upload_to='passport_copies/1/', verbose_name='Topar ýolbaşçysynyň pasport nusgasy (sahypa 1)')),
                ('p_copy_page2_3', models.ImageField(upload_to='passport_copies/2-3/', verbose_name='Topar ýolbaşçysynyň pasport nusgasy (sahypa 2-3)')),
                ('p_copy_page5_6', models.ImageField(upload_to='passport_copies/5-6/', verbose_name='Topar ýolbaşçysynyň pasport nusgasy (sahypa 5-6)')),
                ('p_copy_page32', models.ImageField(upload_to='passport_copies/32/', verbose_name='Topar ýolbaşçysynyň pasport nusgasy (sahypa 32)')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.direction', verbose_name='Ugry')),
            ],
            options={
                'verbose_name': 'taslama',
                'verbose_name_plural': 'taslamalar',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('criteria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.criteria')),
                ('jury', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
            options={
                'verbose_name': 'baha',
                'verbose_name_plural': 'bahalar',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quene_json', models.TextField(verbose_name='Reje JSON-y')),
                ('date', models.DateField(verbose_name='Senesi')),
                ('juries', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Emin agzalar')),
            ],
            options={
                'verbose_name': 'reje',
                'verbose_name_plural': 'rejeler',
            },
        ),
    ]
