# Generated by Django 5.1.1 on 2024-10-22 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ugur')),
            ],
            options={
                'verbose_name': 'ugur',
                'verbose_name_plural': 'ugurlar',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=250, verbose_name='Açar sözi')),
                ('active_jury', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ulanyjy')),
            ],
            options={
                'verbose_name': 'profil',
                'verbose_name_plural': 'profiller',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=200, verbose_name='Edara')),
                ('full_name_of_manager', models.CharField(max_length=200, verbose_name='Topar ýolbaşçysynyň F.A.Aa')),
                ('full_name_of_second_participant', models.CharField(blank=True, max_length=200, null=True, verbose_name='Toparyň ikinji agzasyňyň F.A.Aa')),
                ('full_name_of_third_participant', models.CharField(blank=True, max_length=200, null=True, verbose_name='Toparyň üçinji agzasyňyň F.A.Aa')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Taslamanyň beýany')),
                ('rated', models.BooleanField(default=False)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.direction', verbose_name='Ugry')),
            ],
            options={
                'verbose_name': 'taslama',
                'verbose_name_plural': 'taslamalar',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('jury', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
            options={
                'verbose_name': 'baha',
                'verbose_name_plural': 'bahalar',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quene_json', models.TextField(verbose_name='Reje JSON-y')),
                ('date', models.DateField(verbose_name='Senesi')),
                ('juries', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Emin agzalar')),
            ],
            options={
                'verbose_name': 'reje',
                'verbose_name_plural': 'rejeler',
            },
        ),
    ]
