# Generated by Django 5.1.1 on 2024-10-01 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ugur')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality_type', models.CharField(choices=[('Fiziki', 'fiziki'), ('Ýuridiki', 'ýuridiki')], default='Fiziki', max_length=50, verbose_name='Şahs görnüşi')),
                ('agency', models.CharField(max_length=200, verbose_name='Edara')),
                ('place_of_residence', models.CharField(max_length=200, verbose_name='Ýaşaýan ýeri')),
                ('full_name_of_manager', models.CharField(max_length=200, verbose_name='Topar ýolbaşçysynyň F.A.Aa')),
                ('full_name_of_second_participant', models.CharField(blank=True, max_length=200, null=True, verbose_name='Toparyň ikinji agzasyňyň F.A.Aa')),
                ('full_name_of_third_participant', models.CharField(blank=True, max_length=200, null=True, verbose_name='Toparyň üçinji agzasyňyň F.A.Aa')),
                ('phone_number', models.CharField(max_length=8, verbose_name='Telefon belgi')),
                ('additional_phone_number', models.CharField(max_length=8, verbose_name='Telefon belgi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Taslamanyň beýany')),
                ('directions', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.direction', verbose_name='Ugry')),
            ],
        ),
    ]
