# Generated by Django 5.1.1 on 2024-10-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profil', 'verbose_name_plural': 'profiller'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(max_length=250, verbose_name='Açar sözi'),
        ),
    ]
