# Generated by Django 5.1.1 on 2024-10-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profile_options_alter_profile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.CharField(default='12345', max_length=5, verbose_name='OTP kody'),
            preserve_default=False,
        ),
    ]
