# Generated by Django 5.0 on 2024-10-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project_p_copy_page1_project_p_copy_page2_3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='directions',
            new_name='direction',
        ),
        migrations.AlterField(
            model_name='project',
            name='personality_type',
            field=models.CharField(choices=[('Fiziki', 'Fiziki'), ('Ýuridiki', 'Ýuridiki')], default='Fiziki', max_length=50, verbose_name='Şahs görnüşi'),
        ),
    ]
