# Generated by Django 5.1.1 on 2024-10-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_jury',
            field=models.BooleanField(default=True),
        ),
    ]
